---
# Install all necessary prereqs on the new VM

- name: install pip
  apt: 
    name: python-pip 
    state: present
  become: true

- name: install docker-py
  pip: 
    name: docker-py
    version: 1.7.2
  become: true

- name: install httplib2
  pip: 
    name: httplib2
    version: 0.9.2
  become: true

- name: add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present

- name: install docker
  apt:
    name: docker-engine=1.9.1-0~trusty
    state: present

