#cloud-config

packages:
  - git

runcmd:
  - echo Fetch Autoscaler Repo
  - cd ~ && git clone https://github.com/domdom82/docker-autoscaler.git
  - echo Inject Credentials
  - echo '{{token}}' > ~/docker-autoscaler/tokens/docker-autoscaler
  - echo Launch boot.sh
  - cd ~/docker-autoscaler && ./boot.sh digitalocean
