#cloud-config

packages:
  - git
  - python

runcmd:
  - echo Fetch Autoscaler Repo
  - cd ~root && git clone https://github.com/domdom82/docker-autoscaler.git
  - echo Inject Credentials
  - cd ~/root/docker-autoscaler && ./creds.sh digitalocean {{token}}
  - echo Launch boot.sh
  - cd ~root/docker-autoscaler && ./boot.sh digitalocean
